enyo.depends(
	"dom.css",
	"dom.js",
	"util.js",
	"json.js",
	"xhr.js",
	"Animation.js",
	"Dispatcher.js",
	"ApplicationEvents.js",
	"Gesture.js",
	"DomNode.js",
	"DomNodeBuilder.js",
	"ContainedDomBuilder.js",
	"Control.js"
);
