enyo.palmServices = {
	system: "palm://com.palm.systemservice/",
	telephony: "palm://com.palm.telephony/",
	database: "palm://com.palm.db/",
	application: "palm://com.palm.applicationManager/",
	accounts: "palm://com.palm.service.accounts/",
	downloads: "palm://com.palm.downloadmanager/",
	signal: "palm://com.palm.bus/signal/",
	connection: "palm://com.palm.connectionmanager/",
	display: "palm://com.palm.display/",
	location: "palm://com.palm.location/",
	payment: "palm://com.palm.service.payment",
	crypto: "palm://com.palm.keymanager",
	keys: "palm://com.palm.keys/",
	mediaPermissions: "palm://com.palm.mediapermissions/",
	power: "palm://com.palm.power/",
	printer: "palm://com.palm.printmgr/",
	properties: "palm://com.palm.preferences/systemProperties/",
	sound: "palm://com.palm.audio/systemsounds/",
	zeroconf: "palm://com.palm.zeroconf/",
	bluetooth: "palm://com.palm.bluetooth/",
	bluetoothSPP: "palm://com.palm.service.bluetooth.spp/",
	alarm: "palm://com.palm.power/timeout/",
	activity: "palm://com.palm.activitymanager/"
};