enyo.depends(
	"javascript/g11n.js",
	"javascript/fmts.js",
	"javascript/locale.js",
	"javascript/loadfile.js",
	"javascript/template.js",
	"javascript/resources.js",
	"javascript/character.js",
	"javascript/timezone.js",
	"javascript/datetime.js",
	"javascript/numberfmt.js",
	"javascript/duration.js"
);
