/*$
 * @name areaCodes.js
 * @fileOverview dummy file for localization -- do not list this file in the manifest.json!
 * 
 * 
 */

/*globals $L*/

$L("Chuzhou");
$L("Chuzhou 滁州市");
$L("Hefei");
$L("Hefei 合肥市");
$L("Bengbu");
$L("Bengbu 蚌埠市");
$L("Wuhu");
$L("Wuhu 芜湖市");
$L("Huainan");
$L("Huainan 淮南市");
$L("MaAnshan");
$L("MaAnshan 马鞍山市");
$L("Anqing");
$L("Anqing 安庆市");
$L("Suzhou");
$L("Suzhou 宿州市");
$L("Fuyang");
$L("Fuyang 阜阳市");
$L("Huangshan");
$L("Huangshan 黄山市");
$L("Huaibei");
$L("Huaibei 淮北市");
$L("Tongling");
$L("Tongling 铜陵市");
$L("Xuancheng");
$L("Xuancheng 宣城市");
$L("LiuAn");
$L("LiuAn 六安市");
$L("Chaohu");
$L("Chaohu 巢湖市");
$L("Chizhou");
$L("Chizhou 池州市");
$L("Beijing");
$L("Beijing 北京市");
$L("Chongqing");
$L("Chongqing 重庆市");
$L("Fuzhou");
$L("Fuzhou 福州市");
$L("Xiamen");
$L("Xiamen 厦门市");
$L("Ningde");
$L("Ningde 宁德市");
$L("Putian");
$L("Putian 莆田市");
$L("Quanzhou");
$L("Quanzhou 泉州市");
$L("Zhangzhou");
$L("Zhangzhou 漳州市");
$L("Longyan");
$L("Longyan 龙岩市");
$L("Sanming");
$L("Sanming 三明市");
$L("Nanping");
$L("Nanping 南平市");
$L("Guangzhou");
$L("Guangzhou 广州市");
$L("Shanwei");
$L("Shanwei 汕尾市");
$L("Shantou");
$L("Chaoyang 潮阳市, Shantou 汕头市");
$L("Yangjiang");
$L("Yangjiang 阳江市");
$L("Jieyang");
$L("Jieyang 揭阳市");
$L("Maoming");
$L("Maoming 茂名市");
$L("Jiangmen");
$L("Jiangmen 江门市");
$L("Shaoguan");
$L("Shaoguan 韶关市");
$L("Huizhou");
$L("Huizhou 惠州市");
$L("Meizhou");
$L("Meizhou 梅州市");
$L("Shenzhen");
$L("Shenzhen 深圳市");
$L("Zhuhai");
$L("Zhuhai 珠海市");
$L("Foshan");
$L("Foshan 佛山市, Shunde 顺德市");
$L("Zhaoqing");
$L("Zhaoqing 肇庆市");
$L("Zhanjiang");
$L("Zhanjiang 湛江市");
$L("Zhongshan");
$L("Zhongshan 中山市");
$L("Heyuan");
$L("Heyuan 河源市");
$L("Qingyuan");
$L("Qingyuan 清远市");
$L("Yunfu");
$L("Yunfu 云浮市");
$L("Chaozhou");
$L("Chaozhou 潮州市");
$L("Dongguan");
$L("Dongguan 东莞市");
$L("Linxia");
$L("Linxia 临夏市(临夏 回族自治州)");
$L("Lanzhou");
$L("Lanzhou 兰州市");
$L("Dingxi");
$L("Dingxi 定西县 (定西地区)");
$L("Pingliang");
$L("Pingliang 平凉市 (平凉地区)");
$L("Xifeng");
$L("Xifeng 西峰市 (庆阳地区)");
$L("Jinchang");
$L("Jinchang 金昌市");
$L("Zhangye");
$L("Zhangye 张掖市 (张掖地区)");
$L("Jiuquan");
$L("Jiuquan 酒泉市 (酒泉地区)");
$L("Tianshui");
$L("Tianshui 天水市");
$L("Wudu");
$L("Wudu 武都县 (陇南地区)");
$L("Hezuo");
$L("Hezuo 合作市(甘南 藏族自治州)");
$L("Baiyin");
$L("Baiyin 白银市");
$L("Fangchenggang");
$L("Fangchenggang 防城港市");
$L("Nanning");
$L("Nanning 南宁市");
$L("Liuzhou");
$L("Liuzhou 柳州市");
$L("Guilin");
$L("Guilin 桂林市");
$L("Wuzhou");
$L("Wuzhou 梧州市");
$L("Yulin");
$L("Yulin 玉林市");
$L("Baise");
$L("Baise 百色市 (百色地区)");
$L("Qinzhou");
$L("Qinzhou 钦州市");
$L("Hechi");
$L("Hechi 河池市 (河池地区)");
$L("Beihai");
$L("Beihai 北海市");
$L("Guiyang");
$L("Guiyang 贵阳市");
$L("Zunyi");
$L("Zunyi 遵义市");
$L("Anshun");
$L("Anshun 安顺市 (安顺地区)");
$L("Duyun");
$L("Duyun 都匀市 (黔南布依族 苗族自治州)");
$L("Kaili");
$L("Kaili 凯里市 (黔东南苗族 侗族自治州   )");
$L("Tongren");
$L("Tongren 铜仁市 (铜仁地区)");
$L("Bijie");
$L("Bijie 毕节市 (毕节地区)");
$L("Liupanshui");
$L("Liupanshui 六盘水市");
$L("Xingyi");
$L("Xingyi 兴义市 (黔西南布依族 苗族自治州)");
$L("Wuhan");
$L("Wuhan 武汉市");
$L("Xiangfan");
$L("Xiangfan 襄樊市");
$L("Ezhou");
$L("Ezhou 鄂州市");
$L("Xiaogan");
$L("Xiaogan 孝感市");
$L("Huanggang");
$L("Huanggang 黄冈市");
$L("Huangshi");
$L("Huangshi 黄石市");
$L("Xianning");
$L("Xianning 咸宁市");
$L("Jingzhou");
$L("Jingzhou 荆州市");
$L("Yichang");
$L("Yichang 宜昌市");
$L("Enshi");
$L("Enshi 恩施市 (恩施土家族 苗族自治州)");
$L("Shiyan");
$L("Shiyan 十堰市");
$L("Suizhou");
$L("Suizhou 随州市");
$L("Jingmen");
$L("Jingmen 荆门市");
$L("Xiantao");
$L("Xiantao 仙桃市");
$L("Handan");
$L("Handan 邯郸市");
$L("Shijiazhuang");
$L("Shijiazhuang 石家庄市");
$L("Baoding");
$L("Baoding 保定市");
$L("Zhangjiakou");
$L("Zhangjiakou 张家口市");
$L("Chengde");
$L("Chengde 承德市");
$L("Tangshan");
$L("Tangshan 唐山市");
$L("Langfang");
$L("Langfang 廊坊市");
$L("Cangzhou");
$L("Cangzhou 沧州市");
$L("Hengshui");
$L("Hengshui 衡水市");
$L("Xingtai");
$L("Xingtai 邢台市");
$L("Qinhuangdao");
$L("Qinhuangdao 秦皇岛市");
$L("Shangqiu");
$L("Shangqiu 商丘市");
$L("Zhengzhou");
$L("Zhengzhou 郑州市");
$L("Anyang");
$L("Anyang 安阳市");
$L("Xinxiang");
$L("Xinxiang 新乡市");
$L("Xuchang");
$L("Xuchang 许昌市");
$L("Pingdingshan");
$L("Pingdingshan 平顶山市");
$L("Xinyang");
$L("Xinyang 信阳市、潢川县");
$L("Nanyang");
$L("Nanyang 南阳市");
$L("Kaifeng");
$L("Kaifeng 开封市");
$L("Luoyang");
$L("Luoyang 洛阳市");
$L("Jiaozuo");
$L("Jiaozuo 焦作市");
$L("Hebi");
$L("Hebi 鹤壁市");
$L("Puyang");
$L("Puyang 濮阳市");
$L("Zhoukou");
$L("Zhoukou 周口市");
$L("Luohe");
$L("Luohe 漯河市");
$L("Zhumadian");
$L("Zhumadian 驻马店市");
$L("Sanmenxia");
$L("Sanmenxia 三门峡市");
$L("Harbin");
$L("Harbin 哈尔滨市");
$L("Qiqihar");
$L("Qiqihar 齐齐哈尔市");
$L("Mudanjiang");
$L("Mudanjiang 牡丹江市");
$L("Jiamusi");
$L("Jiamusi 佳木斯市");
$L("Suihua");
$L("Suihua 绥化市");
$L("Heihe");
$L("Heihe 黑河市");
$L("Jiagedaqi");
$L("Jiagedaqi 加格达奇 (大兴安岭地区)");
$L("Yichun");
$L("Yichun 伊春市");
$L("Daqing");
$L("Daqing 大庆市");
$L("Qitaihe");
$L("Qitaihe 七台河市");
$L("Jixi");
$L("Jixi 鸡西市");
$L("Hegang");
$L("Hegang 鹤岗市");
$L("Shuangyashan");
$L("Shuangyashan 双鸭山市");
$L("Yueyang");
$L("Yueyang 岳阳市");
$L("Changsha");
$L("Changsha 长沙市, Xiangtan 湘潭市, Zhuzhou 株州市");
$L("Hengyang");
$L("Hengyang 衡阳市");
$L("Chenzhou");
$L("Chenzhou 郴州市");
$L("Changde");
$L("Changde 常德市");
$L("Yiyang");
$L("Yiyang 益阳市");
$L("Loudi");
$L("Loudi 娄底市");
$L("Shaoyang");
$L("Shaoyang 邵阳市");
$L("Jishou");
$L("Jishou 吉首市 (湘西土家族 苗族自治州)");
$L("Zhangjiajie");
$L("Zhangjiajie 张家界市");
$L("Huaihua");
$L("Huaihua 怀化市");
$L("Yongzhou");
$L("Yongzhou 永州市");
$L("Haikou");
$L("Haikou 海口市");
$L("Changchun");
$L("Changchun 长春市");
$L("Jilin");
$L("Jilin 吉林市");
$L("Hunchun");
$L("Hunchun 珲春市, Yanji 延吉市(延边 朝鲜族自治州)");
$L("Siping");
$L("Siping 四平市");
$L("Tonghua");
$L("Tonghua 通化市, Meihekou 梅河口市");
$L("Baicheng");
$L("Baicheng 白城市");
$L("Liaoyuan");
$L("Liaoyuan 辽源市");
$L("Songyuan");
$L("Songyuan 松原市");
$L("Baishan");
$L("Baishan 白山市");
$L("Nanjing");
$L("Nanjing 南京市");
$L("Wuxi");
$L("Wuxi 无锡市");
$L("Zhenjiang");
$L("Zhenjiang 镇江市");
$L("Suzhou");
$L("Suzhou 苏州市");
$L("Nantong");
$L("Nantong 南通市");
$L("Yangzhou");
$L("Yangzhou 扬州市");
$L("Yancheng");
$L("Yancheng 盐城市");
$L("Xuzhou");
$L("Xuzhou 徐州市");
$L("Huaian");
$L("Huaian 淮阴市");
$L("Lianyungang");
$L("Lianyungang 连云港市");
$L("Changzhou");
$L("Changzhou 常州市");
$L("Taizhou");
$L("Taizhou 泰州市");
$L("Suqian");
$L("Suqian 宿迁市");
$L("Yingtan");
$L("Yingtan 鹰潭市");
$L("Xinyu");
$L("Xinyu 新余市");
$L("Nanchang");
$L("Nanchang 南昌市");
$L("Jiujiang");
$L("Jiujiang 九江市");
$L("Shangrao");
$L("Shangrao 上饶市");
$L("Fuzhou");
$L("Fuzhou 抚州市");
$L("Yichun");
$L("Yichun 宜春市");
$L("JiAn");
$L("JiAn 吉安市");
$L("Ganzhou");
$L("Ganzhou 赣州市");
$L("Jingdezhen");
$L("Jingdezhen 景德镇市");
$L("Pingxiang");
$L("Pingxiang 萍乡市");
$L("Shenyang");
$L("Shenyang 沈阳市");
$L("Tieling");
$L("Tieling 铁岭市");
$L("Dalian");
$L("Dalian 大连市");
$L("Anshan");
$L("Anshan 鞍山市");
$L("Fushun");
$L("Fushun 抚顺市");
$L("Benxi");
$L("Benxi 本溪市");
$L("Dandong");
$L("Dandong 丹东市");
$L("Jinzhou");
$L("Jinzhou 锦州市");
$L("Yingkou");
$L("Yingkou 营口市");
$L("Fuxin");
$L("Fuxin 阜新市");
$L("Liaoyang");
$L("Liaoyang 辽阳市");
$L("Chaoyang");
$L("Chaoyang 朝阳市");
$L("Panjin");
$L("Panjin 盘锦市");
$L("Huludao");
$L("Huludao 葫芦岛市");
$L("Hailaer");
$L("Hailaer 海拉尔市 (呼伦贝尔盟)");
$L("Huhehaote");
$L("Huhehaote 呼和浩特市");
$L("Baotou");
$L("Baotou 包头市");
$L("Wuhai");
$L("Wuhai 乌海市");
$L("Jining");
$L("Jining 集宁市 (乌兰察布盟)");
$L("Chifeng");
$L("Chifeng 赤峰市");
$L("Dongsheng");
$L("Dongsheng 东胜市 (伊克昭盟)");
$L("Linhe");
$L("Linhe 临河市 (巴彦淖尔盟)");
$L("Xilinhaote");
$L("Xilinhaote 锡林浩特市 (锡林郭勒盟)");
$L("Wulanhaote");
$L("Wulanhaote 乌兰浩特市 (兴安盟)");
$L("Alashanzuoqi");
$L("Alashanzuoqi 阿拉善左旗 (阿拉善盟)");
$L("Yinchuan");
$L("Yinchuan 银川市");
$L("Shizuishan");
$L("Shizuishan 石嘴山市");
$L("Wuzhong");
$L("Wuzhong 吴忠市");
$L("Guyuan");
$L("Guyuan 固原县 (固原地区)");
$L("Zhongwei");
$L("Zhongwei 中卫市、中宁县、海原县 (中卫地区)");
$L("Haiyan");
$L("Haiyan 海晏县(海北 藏族自治州)");
$L("Xining");
$L("Xining 西宁市");
$L("PingAn");
$L("PingAn 平安县 (海东地区)");
$L("Tongren");
$L("Tongren 同仁县(黄南 藏族自治州)");
$L("Gonghe");
$L("Gonghe 共和县(海南 藏族自治州)");
$L("Maqin");
$L("Maqin 玛沁县(果洛 藏族自治州)");
$L("Yushu");
$L("Yushu 玉树县(玉树 藏族自治州)");
$L("Delingha");
$L("Delingha 德令哈市 (海西蒙古族 藏族自治州)");
$L("GeErmu");
$L("GeErmu 格尔木市");
$L("Chengdu");
$L("Chengdu 成都市");
$L("Panzhihua");
$L("Panzhihua 攀枝花市");
$L("Zigong");
$L("Zigong 自贡市");
$L("Mianyang");
$L("Mianyang 绵阳市");
$L("Nanchong");
$L("Nanchong 南充市");
$L("Dazhou");
$L("Dazhou 达州市");
$L("Suining");
$L("Suining 遂宁市");
$L("GuangAn");
$L("GuangAn 广安市");
$L("Bazhong");
$L("Bazhong 巴中市");
$L("Luzhou");
$L("Luzhou 泸州市");
$L("Yibin");
$L("Yibin 宜宾市");
$L("Neijiang");
$L("Neijiang 内江市, Ziyang 资阳市");
$L("Leshan");
$L("Leshan 乐山市");
$L("Xichang");
$L("Xichang 西昌市(凉山 彝族自治州)");
$L("YaAn");
$L("YaAn 雅安市");
$L("Kangding");
$L("Kangding 康定县(甘孜 藏族自治州)");
$L("MaErkang");
$L("MaErkang 马尔康县 (阿坝藏族 羌族自治州)");
$L("Deyang");
$L("Deyang 德阳市");
$L("Guangyuan");
$L("Guangyuan 广元市");
$L("Heze");
$L("Heze 荷泽市 (荷泽地区)");
$L("Jinan");
$L("Jinan 济南市");
$L("Qingdao");
$L("Qingdao 青岛市");
$L("Zibo");
$L("Zibo 淄博市");
$L("Dezhou");
$L("Dezhou 德州市 (德州地区)");
$L("Yantai");
$L("Yantai 烟台市");
$L("Weifang");
$L("Weifang 潍坊市");
$L("Jining");
$L("Jining 济宁市");
$L("TaiAn");
$L("TaiAn 泰安市");
$L("Linyi");
$L("Linyi 临沂市 (临沂地区)");
$L("Binzhou");
$L("Binzhou 滨州市 (滨州地区)");
$L("Dongying");
$L("Dongying 东营市");
$L("Weihai");
$L("Weihai 威海市");
$L("Zaozhuang");
$L("Zaozhuang 枣庄市");
$L("Rizhao");
$L("Rizhao 日照市");
$L("Laiwu");
$L("Laiwu 莱芜市");
$L("Liaocheng");
$L("Liaocheng 聊城市 (聊城地区)");
$L("Shanghai");
$L("Shanghai 上海市");
$L("XiAn");
$L("XiAn 西安市, Xianyang 咸阳市");
$L("YanAn");
$L("YanAn 延安市");
$L("Yulin");
$L("Yulin 榆林市");
$L("Weinan");
$L("Weinan 渭南市");
$L("Shangzhou");
$L("Shangzhou 商州市 (商南地区)");
$L("Ankang");
$L("Ankang 安康市 (安康地区)");
$L("Hanzhong");
$L("Hanzhong 汉中市");
$L("Baoji");
$L("Baoji 宝鸡市");
$L("Tongchuan");
$L("Tongchuan 铜川市");
$L("Shuozhou");
$L("Shuozhou 朔州市");
$L("Xinzhou");
$L("Xinzhou 忻州市 (忻州地区)");
$L("Taiyuan");
$L("Taiyuan 太原市");
$L("Datong");
$L("Datong 大同市");
$L("Yangquan");
$L("Yangquan 阳泉市");
$L("Yuci");
$L("Yuci 榆次市 (晋中地区)");
$L("Changzhi");
$L("Changzhi 长治市");
$L("Jincheng");
$L("Jincheng 晋城市");
$L("Linfen");
$L("Linfen 临汾市 (临汾地区)");
$L("Lishi");
$L("Lishi 离石市 (吕梁地区)");
$L("Yuncheng");
$L("Yuncheng 运城市 (运城地区)");
$L("Tianjin");
$L("Tianjin 天津市");
$L("Tacheng");
$L("Tacheng 塔城市");
$L("Hami");
$L("Hami 哈密市 (哈密地区)");
$L("Hetian");
$L("Hetian 和田市 (和田地区)");
$L("Aletai");
$L("Aletai 阿勒泰市");
$L("Atushi");
$L("Atushi 阿图什市 (克孜勒苏柯尔 克孜自治州)");
$L("Bole");
$L("Bole 博乐市 (博尔塔拉 蒙古自治州)");
$L("Kalamayi");
$L("Kalamayi 克拉玛依市");
$L("Urumchi");
$L("Urumchi 乌鲁木齐");
$L("Kuitun");
$L("Kuitun 奎屯市");
$L("Shihezi");
$L("Shihezi 石河子市");
$L("Changji");
$L("Changji 昌吉市(昌吉 回族自治州)");
$L("Tulufan");
$L("Tulufan 吐鲁番市 (吐鲁番地区)");
$L("KuErle");
$L("KuErle 库尔勒市 (巴音郭楞 蒙古自治州)");
$L("Akesu");
$L("Akesu 阿克苏市 (阿克苏地区)");
$L("Kashi");
$L("Kashi 喀什市 (喀什地区)");
$L("Yining");
$L("Yining 伊宁市(伊犁 哈萨克自治州)");
$L("Lhasa");
$L("Lhasa 拉萨市");
$L("Rikaze");
$L("Rikaze 日喀则市 (日喀则地区)");
$L("Naidong");
$L("Naidong 乃东县 (山南地区)");
$L("Linzhi");
$L("Linzhi 林芝县 (林芝地区)");
$L("Changdu");
$L("Changdu 昌都县 (昌都地区)");
$L("Naqu");
$L("Naqu 那曲县 (那曲地区)");
$L("GeEr");
$L("GeEr 噶尔县 (阿里地区)");
$L("Zhongba");
$L("Zhongba 仲巴县");
$L("Jiali");
$L("Jiali 嘉黎县");
$L("Nierong");
$L("Nierong 聂荣县");
$L("Shenzha");
$L("Shenzha 申扎县");
$L("Shuanghu");
$L("Shuanghu 双湖");
$L("Pulan");
$L("Pulan 普兰县");
$L("Zhada");
$L("Zhada 扎达县");
$L("Bange");
$L("Bange 班戈县");
$L("Suoxian");
$L("Suoxian 索县");
$L("Nima");
$L("Nima 尼玛县");
$L("Jinghong");
$L("Jinghong 景洪市 (西双版纳 傣族自治州 )");
$L("Luxi");
$L("Luxi 潞西市 (德宏傣族 景颇族自治州)");
$L("Zhaotong");
$L("Zhaotong 昭通市 (昭通地区)");
$L("Kunming");
$L("Kunming 昆明市");
$L("Dali");
$L("Dali 大理市(大理 白族自治州)");
$L("Gejiu");
$L("Gejiu 个旧市 (红河哈尼族 彝族自治州)");
$L("Qujing");
$L("Qujing 曲靖市");
$L("Baoshan");
$L("Baoshan 保山市");
$L("Wenshan");
$L("Wenshan 文山县 (文山壮族 苗族自治州)");
$L("Yuxi");
$L("Yuxi 玉溪市");
$L("Chuxiong");
$L("Chuxiong 楚雄市(楚雄 彝族自治州 )");
$L("Simao");
$L("Simao 思茅市 (思茅地区)");
$L("Lincang");
$L("Lincang 临沧县 (临沧地区)");
$L("Liuku");
$L("Liuku 六库市(怒江 傈傈族自治州)");
$L("Zhongdian");
$L("Zhongdian 中甸县(迪庆 藏族自治州)");
$L("Lijiang");
$L("Lijiang 丽江纳西族 自治县 (丽江地区)");
$L("Quzhou");
$L("Quzhou 衢州市");
$L("Hangzhou");
$L("Hangzhou 杭州市");
$L("Huzhou");
$L("Huzhou 湖州市");
$L("Jiaxing");
$L("Jiaxing 嘉兴市");
$L("Ningbo");
$L("Ningbo 宁波市");
$L("Shaoxing");
$L("Shaoxing 绍兴市");
$L("Taizhou");
$L("Taizhou 台州市");
$L("Wenzhou");
$L("Wenzhou 温州市");
$L("Lishui");
$L("Lishui 丽水市");
$L("Jinhua");
$L("Jinhua 金华市");
$L("Zhoushan");
$L("Zhoushan 舟山市");

$L("Düsseldorf");
$L("Cologne");
$L("Bonn");
$L("Bonn, Niederkassel-Mondorf");
$L("Aachen-Kornelimünster");
$L("Aachen");
$L("Berlin");
$L("Leipzig");
$L("Dresden");
$L("Lichtenstein");
$L("Krakow");
$L("Krakow am See");
$L("Straßberg");
$L("Strasburg");
$L("Hamburg");
$L("Hamburg, Norderstedt, Neu Wulmstorf");
$L("Bremen");
$L("Kiel");
$L("Hannover");
$L("Essen");
$L("Essen (Oldenburg)");
$L("Göttingen");
$L("Frankfurt");
$L("Frankfurt am Main, Offenbach am Main");
$L("Stuttgart");
$L("Stuttgart, Aichwald, Denkendorf, Esslingen am Neckar, Fellbach, Filderstadt-Bernhausen, Filderstadt-Bonlanden, Filderstadt-Plattenhardt, Korntal, Leinfelden-Echterdingen, Ostfildern-Kemnat, Ostfildern-Nellingen, Ostfildern-Ruit");
$L("Lichtenstein");
$L("Lichtenstein, Engstingen");
$L("Karlsruhe");
$L("Karlsruhe, Eggenstein-Leopoldshafen, Pfinztal-Berghausen (Baden), Rheinstetten, Stutensee,");
$L("Baden-Baden");
$L("Baden-Baden, Sinzheim");
$L("Konstanz");
$L("Konstanz, Reichenau");
$L("Munich");
$L("Nürnberg");
$L("Nürnberg/Fürth");

$L("Cádiz");
$L("Granada");
$L("Murcia");
$L("Baleares");
$L("Zaragoza");
$L("Tarragona");
$L("Madrid");
$L("Alcala de Henares, Arganda, Collado Villalba, Madrid, Madrid");
$L("Alcala de Henares, Aranjuez, Arganda, Buitrago del Lozoya, Collado Villalba, El Escorial, Madrid, El Molar, Navalcarnero, San Martin de Valdeiglesias, Madrid");
$L("Alcala de Henares, Aranjuez, Arganda, Buitrago del Lozoya, Collado Villalba, El Escorial, Madrid, El Molar, Navalcarnero, San Martin de Valdeiglesias, Madrid");
$L("Madrid, Madrid");
$L("Alcala de Henares, Aranjuez, Arganda, Buitrago del Lozoya, Collado Villalba, El Escorial, Madrid, El Molar, Navalcarnero, San Martin de Valdeiglesias, Madrid");
$L("Madrid, El Molar, Madrid");
$L("Aranjuez, Arganda, El Escorial, Madrid, El Molar, Navalcarnero, San Martin de Valdeiglesias, Madrid");
$L("Alcala de Henares, Aranjuez, Arganda, Buitrago del Lozoya, Collado Villalba, El Escorial, Madrid, El Molar, Navalcarnero, San Martin de Valdeiglesias, Madrid");
$L("Ávila");
$L("Seville");
$L("Santa Cruz de Tenerife");
$L("Salamanca");
$L("Toledo");
$L("Ciudad Real");
$L("Las Palmas");
$L("Barcelona");
$L("Barcelona, Granollers, Mataro, Sabadell-Terrassa, Barcelona");
$L("Barcelona, Berga, Caldes de Montbui, Calella, Cardona, Granollers, Igualada, Manlleu, Manresa, Martorell, Mataro, Sabadell-Terrassa, Sallent, Sant Celoni, Vic, Vilafranca del Penedes, Vilanova i la Geltru, Barcelona");
$L("Barcelona, Berga, Granollers, Igualada, Manresa, Martorell, Mataro, Sabadell-Terrassa, Sant Celoni, Vilafranca del Penedes, Vilanova i la Geltru, Barcelona");
$L("Barcelona, Caldes de Montbui, Granollers, Igualada, Manresa, Martorell, Mataro, Sabadell-Terrassa, Vic, Vilafranca del Penedes, Vilanova i la Geltru, Barcelona");
$L("Barcelona, Barcelona");
$L("Barcelona, Berga, Caldes de Montbui, Calella, Cardona, Granollers, Igualada, Manlleu, Manresa, Martorell, Mataro, Sabadell-Terrassa, Sallent, Sant Celoni, Vic, Vilafranca del Penedes, Vilanova i la Geltru, Barcelona");
$L("La Rioja");
$L("Cantabria");
$L("Vizcaya");
$L("Navarra");
$L("Guadalajara");
$L("Almería");
$L("Malaga");
$L("Cordoba");
$L("Valencia");
$L("Alicante");
$L("León");

$L("Freephone");
$L("Freephone services (Numéros Vert)");
$L("French Guiana");
$L("Guadaloupe");
$L("Guadaloupe Island");
$L("Islands of Réunion and Mayotte");
$L("Martinique");
$L("Martinique Island");
$L("Northeast France");
$L("Northwest France");
$L("Paris");
$L("Paris (Ile-de-France area)");
$L("Réunion");
$L("Saint Pierre and Miquelon");
$L("Saint Pierre and Miquelon Islands");
$L("Southeast France");
$L("Southwest France");
$L("Toll call");
$L("Toll calls (Numéros Azur)");
$L("Toll calls (Numéros Indigo)");
$L("Voice over IP");
$L("Voice over IP services");

$L("London");
$L("Birmingham");
$L("Southampton and Portsmouth");
$L("Leeds");
$L("Edinburgh");
$L("Coventry");
$L("Sheffield");
$L("Glasgow");
$L("Nottingham");
$L("Liverpool");
$L("Leicester");
$L("Manchester");
$L("Bristol");
$L("Northern Ireland");
$L("Reading");
$L("Cardiff");
$L("Cambridge");
$L("Aberdeen");
$L("Bath");
$L("Canterbury");
$L("Brighton");
$L("Buckingham");
$L("Dover");
$L("Unknown Location");

$L("Dublin");

$L("New Delhi");
$L("New Delhi, New Delhi");
$L("Kolkata");
$L("Kolkata, Kolkata");
$L("Mumbai");
$L("Mumbai, Mumbai");
$L("Bangalore");
$L("Bangalore, Bangalore");
$L("Chennai");
$L("Chennai, Chennai");
$L("Hyderabad");
$L("Hyderabad West (Shamshabad), Hyderabad");
$L("Hyderabad East (Ghatkeswar), Hyderabad");

$L("Genoa");
$L("Turin");
$L("Turin, Ivrea");
$L("Courmayeur");
$L("Courmayeur, Aosta Valley");
$L("Milan");
$L("Trieste");
$L("Venice");
$L("Padua");
$L("Pisa");
$L("Bologna");
$L("San Marino");
$L("Republic of San Marino");
$L("Florence");
$L("Siena");
$L("Rome");
$L("Rome, Vatican City");
$L("Rome, Tivoli");
$L("Naples");

$L("Genoa, Moncalieri");
$L("Saint Vincent");
$L("Saint Vincent, Cervinia, Aosta Valley");
$L("Portofino, Genoa");
$L("Milan");
$L("Milan, Rho, Saronno, Varese, Como");
$L("Brescia, Lake Garda, Valle Sabbia, Salò");
$L("San Donà di Piave, Venice");
$L("Bolzano");
$L("Bolzano/Bozen");
$L("Florence, Sesto Fiorentino");
$L("Naples, Capri, Aversa, Castellamare di Stabia, Nocera Inferiore, Pompei, Pozzuoli, Sorrento, Torre Annunziata, Torre dei Greco");
$L("San Severo, Foggia Apricena, San Giovanni Rotondo, Tremiti isles");

$L("Mexico City");
$L("Mexico City, Federal District");


$L("New Jersey");
$L("New Jersey: Hackensack, Jersey City, Hoboken, Bayonne, Ridgewood, Union City, Teaneck, New Milford, and northeast New Jersey");
$L("Washington");
$L("Washington D.C.");
$L("Connecticut");
$L("Connecticut: Bridgeport, Danbury, New Haven, Waterbury, Southwestern Connecticut");
$L("Manitoba");
$L("Manitoba, Canada");
$L("Alabama");
$L("Alabama: Birmingham; Tuscaloosa; western and central Alabama");
$L("Washington");
$L("Washington: Seattle");
$L("Maine");
$L("Idaho");
$L("California");
$L("California: Stockton, Modesto, Merced, Tracy, San Andreas and central California");
$L("Texas");
$L("Texas: San Antonio area");
$L("New York");
$L("New York: Manhattan except for Marble Hill");
$L("S California");
$L("Southern California: Central Los Angeles");
$L("Texas");
$L("Texas: Dallas area");
$L("Pennsylvania");
$L("Pennsylvania: Philadelphia");
$L("Ohio");
$L("Ohio: Cleveland");
$L("Illinois");
$L("Central Illinois: Springfield, Champaign Decatur, Urbana, Lincoln");
$L("N Minnesota");
$L("Northern Minnesota: Duluth, Thief River Falls, Brainerd, International Falls");
$L("NW Indiana");
$L("Northwest Indiana: Gary, Chesterton, Crown Point, East Chicago, Hammond, Hobart, Merrillville, Michigan City, Portage, Valparaiso");
$L("Illinois");
$L("E Louisiana");
$L("Central Eastern Louisiana: Baton Rouge, Donaldsonville, New Roads, White Castle");
$L("Ontario");
$L("Ontario, Canada");
$L("Maryland");
$L("S Mississippi");
$L("Southern Mississippi: Gulfport, Biloxi, Pascagoula, Bay St Louis");
$L("SW Georgia");
$L("Southwestern Georgia: Albany, Valdosta, Bainbridge, Americus, Fitzgerald");
$L("NW Michigan");
$L("Northwestern Michigan: Muskegon, Traverse City, Ludington, Petoskey");
$L("Ohio");
$L("British Columbia");
$L("British Columbia, Canada");
$L("SW Florida");
$L("Southwestern Florida: Lee, Collier, and Monroe Counties; Cape Coral, Fort Myers, Naples, Everglades");
$L("Maryland");
$L("Bahamas");
$L("The Bahamas");
$L("Barbados");
$L("Michigan");
$L("Michigan: Oakland County");
$L("Ontario");
$L("Ontario, Canada");
$L("British Columbia");
$L("British Columbia: Victoria, Prince George, Prince Rupert, Kelowna; also Hyder, Alaska.");
$L("SW Alabama");
$L("Southwestern Alabama: Mobile, Jackson, Brewton");
$L("NE North Carolina");
$L("Northeastern North Carolina: Greenville, Kitty Hawk, Rocky Mount");
$L("Washington");
$L("Washington: Tacoma, Lakewood, Auburn, Puyallup, Enumclaw, Spanaway and south Seattle suburbs");
$L("Texas");
$L("Texas: Waco, Killeen, Temple, Belton, and Stephenville");
$L("NE Alabama");
$L("Northern and Eastern Alabama: Huntsville, Decatur, Cullman, Gadsden, Florence, Anniston");
$L("NE Indiana");
$L("Northeastern Indiana: Fort Wayne, New Haven, Decatur, Angola, Huntington, Wabash");
$L("SE Wisconsin");
$L("Southeastern Wisconsin: Racine, Kenosha, Menomonee Falls, Waukesha");
$L("Anguilla");
$L("Pennsylvania");
$L("Antigua/Barbuda");
$L("Antigua and Barbuda");
$L("SW Michigan");
$L("Southwestern Michigan: Battle Creek, Kalamazoo, Benton Harbor, Allegan, Hastings, St Joseph");
$L("W Kentucky");
$L("Western Kentucky: Owensboro, Paducah, Bowling Green, Hopkinsville, Henderson, Elizabethtown");
$L("Wisconsin");
$L("SW Virginia");
$L("Southwestern Virginia: Bristol, Abingdon, Wytheville, Martinsville, Bluefield");
$L("Texas");
$L("Texas: Houston");
$L("SW Ohio");
$L("Southwestern Ohio");
$L("BVIs");
$L("The British Virgin Islands");
$L("Ontario");
$L("Ontario, Canada");
$L("W Maryland");
$L("Western Maryland: Silver Spring, DC suburbs, Hagerstown, Frederick, Rockville, Cumberland");
$L("Delaware");
$L("Colorado");
$L("Central Colorado: Denver, Boulder, Longmont, Aurora");
$L("West Virginia");
$L("S Florida");
$L("Southern Florida: Miami-Dade, Florida Keys, Miami, Homestead, Coral Gables, Key West");
$L("Saskatchewan");
$L("Saskatchewan, Canada");
$L("Wyoming");
$L("W Nebraska");
$L("Western Nebraska: North Platte, Scottsbluff, McCook, Kearney, Grand Island");
$L("W Illinois");
$L("Central Western Illinois: Peoria, Bloomington-Normal, Moline, Rock Island, Galesburg");
$L("S California");
$L("Southern California: Santa Monica, Malibu, Torrance, South Bay, Beverly Hills, Catalina Island, the Los Angeles Westside");
$L("Illinois");
$L("Illinois: Chicago");
$L("Michigan");
$L("Michigan: Dearborn, Detroit, Hamtramck, Highland Park");
$L("Missouri");
$L("Missouri: St. Louis, Florissant, Crestwood, Affton");
$L("New York");
$L("North Central New York: Syracuse, New York, Utica, Watertown");
$L("Kansas");
$L("Kansas: Wichita, Augusta, El Dorado, Mulvane");
$L("Indiana");
$L("Central Indiana: Indianapolis, Carmel, Fishers, Noblesville, Greenwood, Mooresville, Beech Grove");
$L("N Louisiana");
$L("Northern Louisiana: Shreveport, Monroe, Alexandria, Fisher, Tallulah");
$L("E Iowa");
$L("Eastern Iowa: Cedar Rapids, Waterloo, Burlington, Iowa City");
$L("Minnesota");
$L("Central Minnesota: St. Cloud, Alexandria, Morris, Hutchinson, Sandstone, Appleton");
$L("E Florida");
$L("Central Eastern Florida: Orlando, Cocoa Beach, St Cloud");
$L("S California");
$L("Southern California: Los Angeles, West LA, San Fernando Valley, Florence, Montebello");
$L("Texas");
$L("Texas: Abilene, San Angelo, Sweetwater, Snyder");
$L("E Arkansas");
$L("Eastern Arkansas: Texarkana, Jonesboro, Pine Bluff");
$L("NE Ohio");
$L("Northeastern Ohio: Akron, Canton, Youngstown, Warren");
$L("Illinois");
$L("Illinois: Aurora, Naperville, western Chicago");
$L("SE Alabama");
$L("Southeastern Alabama: Montgomery, Auburn, Opelika, Dothan, Selma");
$L("North Carolina");
$L("North Carolina: Greensboro, Winston-Salem, Wilkesboro, Roxboro, and northwest North Carolina");
$L("SW Louisiana");
$L("Southwestern Louisiana: Lafayette, Lake Charles, Leesville, New Iberia, Opelousas, De Ridder");
$L("Massachusetts");
$L("U.S. Virgins");
$L("The U.S. Virgin Islands");
$L("California");
$L("California: East Bay Area, Oakland, Berkeley, Alameda");
$L("E Ontario");
$L("Eastern Ontario, Canada: Ottawa");
$L("Caymans");
$L("The Cayman Islands");
$L("New York");
$L("New York: The \"Outer Boroughs\"");
$L("Massachusetts");
$L("Florida");
$L("Central Florida: Gainesville, Ocala, Inverness, Dunnellon");
$L("W Washington");
$L("Western Washington: Olympia, Vancouver, Bellingham, Bremerton, Port Angeles, Aberdeen");
$L("SW Texas");
$L("Western and Southern Texas: Corpus Christi, Victoria, George");
$L("Kentucky");
$L("Kentucky: west of the Pennyrile Parkway, including Fort Campbell, Henderson, Hopkinsville, Madisonville, Murray, and Paducah");
$L("NW California");
$L("Northwest California");
$L("Ohio");
$L("Utah");
$L("NE Florida");
$L("Northern and Eastern Florida: Daytona Beach, Lake City, Live Oak, Crescent City");
$L("Rhode Island");
$L("E Nebraska");
$L("Eastern Nebraska: Omaha, Lincoln, Norfolk, Superior");
$L("S Alberta");
$L("Southern Alberta, Canada: Calgary, Banff, Red Deer, Medicine Hat, Lethbridge, Brooks");
$L("Georgia");
$L("Georgia: Atlanta");
$L("Oklahoma");
$L("Central Oklahoma: Oklahoma City, Stillwater, Edmond, Norman, Shawnee, Chickasha");
$L("Montana");
$L("E Florida");
$L("Central Eastern Florida: Orlando, Florida, St. Cloud");
$L("California");
$L("Central California: San Jose, Los Gatos, Milpitas, Sunnyvale, Cupertino, Gilroy");
$L("SE Texas");
$L("Southeastern Texas: Beaumont, Galveston, Port Arthur, Jasper");
$L("E Maryland");
$L("Eastern Maryland: Baltimore, Annapolis, Salisbury");
$L("W Pennsylvania");
$L("Western Pennsylvania: Pittsburgh area, McKeesport, Braddock, Duquesne");
$L("W Massachusetts");
$L("Western Massachusetts: Springfield, Pittsfield, Holyoke, Greenfield");
$L("Wisconsin");
$L("Wisconsin: Milwaukee");
$L("California");
$L("Central California: San Francisco, Marin County");
$L("Ontario");
$L("Ontario: Toronto");
$L("SW Missouri");
$L("Southwestern Missouri: Springfield, Joplin, Branson, West Plains, Lamar, Lebanon");
$L("Quebec");
$L("Quebec, Canada: Quebec City, Saguenay, Gaspé Peninsula, Côte-Nord, Chibougamau, St-Georges");
$L("NW Ohio");
$L("Northwestern Ohio: Toledo, Sylvania, Mansfield, Lima, Findlay, Bryan, Sandusky, Bowling Green");
$L("E Tennessee");
$L("Eastern Tennessee: Bristol, Johnson City, Kingsport; Chattanooga, Cleveland");
$L("California");
$L("Washington");
$L("Washington: Seattle suburbs, Bellevue, Everett, Redmond, Renton, Kirkland, Bothell, Sammamish, Issaquah, Edmonds, Lynnwood and Mountlake Terrace");
$L("Texas");
$L("W Texas");
$L("West Texas: Midland, Odessa, Big Spring, Alpine");
$L("S Virginia");
$L("Southern Virginia: Charlottesville, Lynchburg, Danville, Farmville, South Hill");
$L("Utah");
$L("Utah: Cedar City, Logan, Moab, Park City, St. George, Moab");
$L("Quebec");
$L("Quebec, Canada");
$L("N Ohio");
$L("Northern Ohio: Cleveland suburbs, Elyria, Lorain, Oberlin, Ashtabula");
$L("Bermuda");
$L("California");
$L("Maryland");
$L("Illinois");
$L("S Quebec");
$L("Central Southern Quebec, Canada: Laval, Montreal suburbs");
$L("Inbound Intl.");
$L("Inbound international calls for carrier-specific services");
$L("Oregon");
$L("Oregon: Eugene, Medford, Bend, Pendleton, Corvallis, Ontario, Burns");
$L("Illinois");
$L("Texas");
$L("Georgia");
$L("Grenada");
$L("Connecticut");
$L("Georgia");
$L("Central Georgia: Macon, Warner Robins, Swainsboro, Wadley, Milledgeville, Perry");
$L("NW Arkansas");
$L("Northwestern Arkansas: Fort Smith, Fayetteville");
$L("Arizona");
$L("Arizona: Mesa, Scottsdale, Chandler, Gilbert, Tempe, Queen Creek, eastern Phoenix suburbs");
$L("Pennsylvania");
$L("Personal Comm.");
$L("Personal Communications Services");
$L("Arkansas");
$L("Central Arkansas: Little Rock, Hot Springs");
$L("N Kentucky");
$L("Northern Kentucky: Louisville, Frankfort, Shelbyville, Bardstown");
$L("NW Oregon");
$L("Northwestern Oregon: Portland, Salem, Hillsboro, St. Helens, Tillamook, Astoria");
$L("Louisiana");
$L("Louisiana: New Orleans, Metairie, Kenner");
$L("NW New Mexico");
$L("Northwestern New Mexico: Albuquerque, Santa Fe, Farmington, Gallup");
$L("New Brunswick");
$L("New Brunswick, Canada");
$L("S Minnesota");
$L("Southern Minnesota: Rochester, Mankato, Worthington, Marshall");
$L("SE Massachusetts");
$L("Southeastern Massachusetts: Worcester, New Bedford");
$L("E Washington");
$L("Eastern Washington: Spokane, the Tri-Cities, Yakima, Wenatchee, Walla Walla, Pullman, Ellensburg");
$L("California");
$L("Central California: Oakland, Fremont, Hayward, Castro Valley, Alameda, Berkeley, Richmond");
$L("Texas");
$L("Central Texas: Austin, San Marcos, Lampasas, Bastrop, Milam");
$L("SW Ohio");
$L("Southwestern Ohio: Cincinnati, Middletown, Hamilton, Norwood, Lebanon");
$L("Quebec");
$L("Quebec, Canada: Montreal, Île Perrot,  Île Bizard");
$L("Iowa");
$L("North Central Iowa: Des Moines, Ames, Fort Dodge, Jefferson, Algona, Indianola");
$L("New York");
$L("New York: Nassau County, Hempstead, Elmont");
$L("Michigan");
$L("South Central Michigan: Lansing, Jackson, Charlotte, Coldwater, Howell, Deerfield, Addison");
$L("NE New York");
$L("Northeastern New York: Albany, Schenectady, Plattsburgh, Saranac Lake");
$L("SW Ontario");
$L("Southwestern Ontario, Canada: London, Windsor, Kitchener-Waterloo, Cambridge");
$L("SE Arizona");
$L("Southeastern Arizona: Tucson, Nogales");
$L("Personal Comm.");
$L("Personal Communications Services");
$L("NE California");
$L("Northerneastern California: Redding, Chico, Davis, Placerville, Lake Tahoe, Susanville, Alturas, Truckee");
$L("Nebraska");
$L("Personal Comm.");
$L("Personal Communications Services");
$L("Wisconsin");
$L("Oklahoma");
$L("Virginia");
$L("North Central Virginia: Roanoke, Fredericksburg, Blacksburg, Harrisonburg, Winchester");
$L("Oregon");
$L("Oregon: Eugene, Medford, Bend, Pendleton, Corvallis, Ontario, Burns");
$L("Personal Comm.");
$L("Personal Communications Services");
$L("New Jersey");
$L("Dir. Assistance");
$L("Directory Assistance Applications");
$L("Missouri");
$L("California");
$L("Central California: Fresno, Visalia, Madera, Hanford, Tulare");
$L("Florida");
$L("Florida: Palm Beach, West Palm Beach, Boca Raton, Boynton Beach, Delray Beach, Belle Glade");
$L("S California");
$L("Southern California: Long Beach, Whittier, Norwalk, La Habra Lakewood, Bellflower");
$L("E Iowa");
$L("Eastern Iowa: Davenport, Dubuque, Bettendorf, Decorah, Clinton");
$L("Washington");
$L("Washington: Western Washington");
$L("Personal Comm.");
$L("Personal Communications Services");
$L("Ohio");
$L("NE Pennsylvania");
$L("Northeastern Pennsylvania: Scranton, Williamsport, Wilkes-Barre, Nanticoke, Hazleton, Pottsville, Sunbury, Danville, Bloomsburg, Stroudsburg");
$L("Virginia");
$L("Missouri");
$L("Missouri: Columbia, Jefferson City, Hannibal, Cape Girardeau, Poplar Bluff, Farmington, Park Hills, Lake Ozark and eastern Missouri excluding St. Louis");
$L("Indiana");
$L("North Central Indiana: South Bend, Logansport, Elkhart, Warsaw, Nappanee");
$L("New Mexico");
$L("New Mexico: Las Cruces, Roswell, Carlsbad, Taos");
$L("Personal Comm. Services");
$L("Personal Communications Services");
$L("Quebec");
$L("Quebec, Canada");
$L("SW Oklahoma");
$L("Southern and Western Oklahoma: Enid, Lawton, Ponca City, Guymon, Ardmore, Sayre, Elk City");
$L("Quebec");
$L("Quebec, Canada");
$L("W New York");
$L("Western New York: Rochester, Wellsville, Batavia");
$L("Michigan");
$L("Michigan: Warren, Sterling Heights, Macomb County");
$L("Alberta");
$L("Alberta, Canada");
$L("Personal Comm.");
$L("Personal Communications Services");
$L("Special Telecom.");
$L("Special Telecommunications Needs in Canada");
$L("Mississippi");
$L("Central Mississippi: Jackson, Meridian, Natchez, McComb, Hattiesburg");
$L("Arizona");
$L("Arizona: Phoenix");
$L("New Hampshire");
$L("British Columbia");
$L("British Columbia: Vancouver, Abbotsford, Whistler, Chilliwack");
$L("South Dakota");
$L("E Kentucky");
$L("Eastern Kentucky: Ashland, Hazard, Somerset, London, Corbin, Pikeville, Maysville");
$L("New York");
$L("New York: Binghamton, Elmira, Bath, Norwich, Oneonta, Ithaca");
$L("SW Wisconsin");
$L("Southwestern Wisconsin: Madison, La Crosse, Platteville, Beloit");
$L("SE New Jersey");
$L("Central and Southeastern New Jersey: Atlantic City, Trenton");
$L("SE Pennsylvania");
$L("Southeastern Pennsylvania: Allentown, Reading, Norristown, Chester");
$L("Minnesota");
$L("Minnesota: Minneapolis, Fort Snelling, St Anthony, Richfield");
$L("E Ontario");
$L("Eastern Ontario, Canada: Ottawa, Kingston");
$L("Ohio");
$L("Ohio: Columbus");
$L("Tennessee");
$L("North Central Tennessee: Nashville, Murfreesboro, Springfield, Lebanon, Dickson");
$L("SW Michigan");
$L("Southwestern Michigan: Grand Rapids, Holland, Greenville, Grand Haven, Zeeland, Ionia");
$L("E Massachusetts");
$L("Eastern Massachusetts: Boston, Cambridge");
$L("S Illinois");
$L("Southern Illinois: Alton, Belleville, Carbondale, Centralia, East Saint Louis, Mount Vernon");
$L("S California");
$L("Southern California: San Diego, Chula Vista");
$L("S Kansas");
$L("Southern Kansas: Dodge City, Emporia, Geat Bend, Parsons, Liberal");
$L("Arizona");
$L("Arizona: Glendale, Sun City, Buckeye, Peoria, western Phoenix suburbs");
$L("S California");
$L("Southern California: Pasadena, West Covina, El Monte, La Puente, Arcadia, San Gabriel Valley, eastern Los Angeles suburbs");
$L("N California");
$L("Northern California coast");
$L("California");
$L("Central California: San Francisco");
$L("Illinois");
$L("Illinois: Aurora, Naperville, western Chicago suburbs");
$L("New York");
$L("New York: Suffolk County");
$L("Missouri");
$L("East Central Missouri: St. Charles, Chesterfield, Union, De Soto, Troy");
$L("Iowa");
$L("Central Iowa: Mason City, Oskaloosa, Creston, Pella, Ottumwa, Britt, Clear Lake, Fairfield");
$L("New York");
$L("New York: Manhattan");
$L("Ontario");
$L("Ontario, Canada");
$L("Turks/Caicos");
$L("The Turks and Caicos Islands");
$L("California");
$L("Central California: San Mateo, Palo Alto, Redwood City, Menlo Park, Mountain View, southern San Francisco suburbs");
$L("Minnesota");
$L("East Central Minnesota: St Paul, Lindstrom, Red Wing, Hastings");
$L("California");
$L("Alabama");
$L("Missouri");
$L("North Central Missouri: Sedalia, Kirksville, Macon, Marshall, Trenton, Maryville, Bethany");
$L("S California");
$L("South Central California: Bakersfield, Lancaster, Santa Clarita, Palmdale, Mojave");
$L("N Mississippi");
$L("Northern Mississippi: Greenville, Tupelo, Winona, Columbus, Holly Springs");
$L("Montserrat");
$L("Maryland");
$L("California");
$L("Central California: San Jose");
$L("Marianas");
$L("Northern Mariana Islands");
$L("Guam");
$L("Georgia");
$L("Michigan");
$L("West Virginia");
$L("Texas");
$L("Amer. Samoa");
$L("American Samoa");
$L("Florida");
$L("LD Carrier");
$L("Long Distance Carrier Use");
$L("North Dakota");
$L("Nevada");
$L("Nevada: Clark County, Las Vegas, Henderson, Boulder City");
$L("N Virginia");
$L("Northern Virginia: Alexandria, Arlington, Fairfax, Prince William, eastern Loudoun counties");
$L("North Carolina");
$L("South Central North Carolina: Charlotte, Gastonia, Concord, Salisbury");
$L("Ontario");
$L("Central Ontario, Canada: Sudbury, Sault Ste. Marie, North Bay, Timmins, Barrie");
$L("Georgia");
$L("West Central Georgia: Augusta, Lincolnton, Columbus, LaGrange, Rome, Dalton, Thomaston");
$L("NW California");
$L("Northwestern California: Napa, Vallejo, Santa Rosa, Ukiah, Crescent City, Eureka, Ukiah");
$L("Illinois");
$L("Illinois: Chicago Heights, Evergreen Park, Tinley Park, Elmwood Park, Cicero, Oak Forest, Oak Park, Berwyn, western Chicago suburbs");
$L("Newfoundland");
$L("Newfoundland and Labrador, Canada: St. John's");
$L("U.S. Government");
$L("U.S. Government Special Services");
$L("W Iowa");
$L("Western Iowa: Sioux City, Council Bluffs, Sheldon, Denison, Estherville");
$L("Texas");
$L("Texas: Houston");
$L("S California");
$L("Southern California: Anaheim, Santa Ana, Huntington Beach, Orange, Garden Grove, Fullerton, Orange County");
$L("N Wisconsin");
$L("Northern Wisconsin: Wausau, Eau Claire, Rice Lake, Rhinelander, Ashland");
$L("W New York");
$L("Western New York: Buffalo, Jamestown, Niagara Falls, Tonawanda, Olean");
$L("Pennsylvania");
$L("South Central Pennsylvania: Harrisburg, Gettysburg, Lancaster, York");
$L("New York");
$L("New York: New York City, Marble Hill");
$L("SE Colorado");
$L("Southeastern Colorado: Colorado Springs, Pueblo, Leadville, Trinidad, Rocky Ford, La Junta");
$L("Colorado");
$L("Sint Maarten");
$L("SW Pennsylvania");
$L("Southwestern Pennsylvania: New Castle, Washington, Indiana, Uniontown");
$L("Florida");
$L("Central Florida: St Petersburg, Dunedin");
$L("Illinois");
$L("W Tennessee");
$L("Western Tennessee: Union City, Jackson, Dyersburg, Martin, Brownsville, Paris, Bolivar");
$L("New Jersey");
$L("East Central New Jersey: New Brunswick, Neptune, Freehold, Lakewood");
$L("SW Michigan");
$L("Southwestern Michigan: Ann Arbor, Canton, Plymouth, Monroe, Wayne, Ypsilanti, Romulus, Detroit suburbs");
$L("Texas");
$L("SE Ohio");
$L("Central and Southeastern Ohio: Columbus, Newark, Lancaster, Delaware, Mt. Vernon, Marion, Washington C.H., Marietta, Portsmouth, Cambridge, Zanesville, Coshocton, Stuebenville, Athens");
$L("S California");
$L("Southern California: San Fernando Valley");
$L("Florida");
$L("Virginia");
$L("Virginia: Hampton Roads, Eastern Shore");
$L("St. Lucia");
$L("Saint Lucia");
$L("SE California");
$L("Southeastern California: Bishop, Ridgecrest, Barstow, Palm Springs, Indio, Imperial County");
$L("Georgia");
$L("Minnesota");
$L("Minnesota: Maple Grove, Monticello, Elk River, Fridley, Blaine, northwest Minneapolis");
$L("California");
$L("Central California: Oakland, Berkeley, Alameda");
$L("Indiana");
$L("Central Indiana: Lafayette, Marion, Muncie, Richmond");
$L("Dominica");
$L("Commonwealth of Dominica");
$L("Mississippi");
$L("N Georgia");
$L("Central North Georgia: Marietta, Cedartown, Gainesville, Atlanta suburbs");
$L("E Florida");
$L("Central Eastern Florida: Vero Beach, Port Saint Lucie, Fort Pierce, Sebastian, Stuart");
$L("Illinois");
$L("Illinois: Chicago");
$L("Massachusetts");
$L("Nevada");
$L("Nevada: Reno, Elko, Ely");
$L("British Columbia");
$L("Illinois");
$L("N Alberta");
$L("Northern Alberta, Canada: Edmonton, Jasper, Grande Prairie, Peace River");
$L("E Massachusetts");
$L("Eastern Massachusetts: Saugus, Norwood, Waltham, Woburn, Boston suburbs");
$L("St. Vincent/Grenadines");
$L("Saint Vincent and the Grenadines");
$L("N Kansas");
$L("Northern Kansas: Colby, Topeka, Salina, Manhattan, Lawrence");
$L("Florida");
$L("Florida: Miami-Dade County, Florida Keys");
$L("Puerto Rico");
$L("Toll-free");
$L("Toll-free Telephone Service");
$L("Utah");
$L("Utah: Wasatch Front");
$L("Vermont");
$L("South Carolina");
$L("Central South Carolina: Columbia, Rock Hill, Sumter, Aiken");
$L("Virginia");
$L("Virginia: Richmond, Petersburg");
$L("California");
$L("Central Coastal California: Ventura, San Luis Obispo, Santa Barbara, Oxnard, Simi Valley");
$L("Texas");
$L("Texas: Amarillo, Lubbock, Canadian, Perryton, Shamrock, Dalhart, Texas Panhandle");
$L("NW Ontario");
$L("Northwestern Ontario, Canada: Thunder Bay, Kenora, Dryden, Greenstone");
$L("Hawaii");
$L("D.R.");
$L("Dominican Republic");
$L("Michigan");
$L("Michigan: Port Huron, Flint, Lapeer, and Michigan \"Thumb\"");
$L("Indiana");
$L("Indiana: Southern Indiana, including Bloomington, Evansville, Jeffersonville, New Albany, and Terre Haute).");
$L("Florida");
$L("Central Florida: Tampa, Temple Terrace, Plant City, Pasco County, Oldsmar");
$L("NW Pennsylvania");
$L("Northwestern and Central Pennsylvania: Erie, Warren, State College, Altoona, Johnstown, Meyersdale, Johnsonburg, St. Marys, Ridgway, DuBois, Emporium");
$L("N Illinois");
$L("Northern Illinois: Rockford, La Salle, De Kalb, Freeport, Joliet, Plainfield, Crystal Lake");
$L("Missouri");
$L("West Central Missouri: Kansas City, St Joseph, Independence, Harrisonville");
$L("Texas");
$L("Texas: Fort Worth, Arlington, Grandview, Weatherford, Rhome");
$L("S California");
$L("Southern California: San Fernando Valley, including Glendale, San Fernando, Northridge, Burbank, Los Angeles suburbs");
$L("Quebec");
$L("Quebec, Canada: Sherbrooke, Trois-Rivieres, Abitibi-Témiscamingue, Mauricie, Outaouais, Estrie");
$L("Alberta");
$L("Alberta, Canada");
$L("W North Carolina");
$L("Western North Carolina: Hickory, Asheville, Waynesville, Franklin, Murphy");
$L("D.R.");
$L("The Dominican Republic");
$L("SW Texas");
$L("Southwestern Texas: Del Rio, Uvalde, New Braunfels, Kerrville, Eagle Pass");
$L("California");
$L("Central California: Salinas, Hollister, Monterey, Carmel, Santa Cruz");
$L("Texas");
$L("E South Carolina");
$L("Eastern South Carolina: Florence, Myrtle Beach, Charleston, Isle of Palms, Hilton Head Island");
$L("SE New York");
$L("Southeastern New York: Rockland, Poughkeepsie, Middletown, West Point, Newburgh, Catskills, Margaretville");
$L("NE Illinois");
$L("Northeastern Illinois: Arlington Heights, Buffalo Grove, Wauconda, Waukegan, Des Plaines, Chicago suburbs");
$L("New Jersey");
$L("D.R.");
$L("The Dominican Republic");
$L("NW Florida");
$L("Northwestern Florida: Pensacola, Tallahassee, Panama City, the Florida panhandle");
$L("SW New Jersey");
$L("Southwestern New Jersey: Vineland, Cherry Hill, Camden, Millville");
$L("Massachusetts");
$L("S California");
$L("Southern California: Del Mar, La Jolla, San Diego");
$L("Kentucky");
$L("North Central Kentucky: Lexington, Richmond, Danville, Covington, Florence, Mount Sterling");
$L("Connecticut");
$L("Connecticut: Bristol, Hartford, Norwich and northern and eastern Connecticut");
$L("New Jersey");
$L("Florida");
$L("South Central Florida: Auburndale, Lakeland, Avon Park, Clewiston, Bartow, Sebring, Winter Haven");
$L("South Carolina");
$L("South Carolina: Greenville, Spartanburg, Anderson, Upstate South Carolina");
$L("E Tennessee");
$L("Central Eastern Tennessee: Knoxville, Gatlinburg, Newport, Jefferson City, Oak Ridge, Rockwood");
$L("Yukon");
$L("Yukon, Northwest Territories, and Nunavut, Canada");
$L("Trinidad/Tobago");
$L("Trinidad and Tobago");
$L("St. Kitts/Nevis");
$L("Saint Kitts and Nevis");
$L("S Arkansas");
$L("Southern and Eastern Arkansas: Texarkana, Jonesboro, Pine Bluff");
$L("Illinois");
$L("Quebec");
$L("Quebec, Canada");
$L("Jamaica");
$L("Pennsylvania");
$L("Toll-free Telephone Service");
$L("Premium-rate");
$L("Premium-rate Telephone Service");
$L("SW Tennessee");
$L("Southwestern Tennessee: Memphis, Covington, Somerville");
$L("Nova Scotia/PEI");
$L("Nova Scotia and Prince Edward Island, Canada");
$L("NE Texas");
$L("Northeastern Texas: Tyler, Sherman, Longview, Marshall, Palestine, Jacksonville, Carthage");
$L("NE Florida");
$L("Northeastern Florida: Jacksonville, St. Augustine, Starke, Green Cove Springs");
$L("SW Ontario");
$L("Southwestern Ontario, Canada: Niagara Region, Hamilton, Toronto suburbs");
$L("N Michigan");
$L("Northern Michigan: Escanaba, Houghton, Iron Mountain, Marquette, Menominee, Sault Ste. Marie, Upper Peninsula");
$L("Alaska");
$L("Alaska: Anchorage, Juneau, Fairbanks");
$L("New Jersey");
$L("West Central New Jersey: Alpha, Washington, Elizabeth, Warren, Plainfield");
$L("S California");
$L("Southern California: Colton, Grand Terrace, Ontario, Claremont, Pomona, Chino, Redlands, Fontana");
$L("SE North Carolina");
$L("Southeastern North Carolina: Fayetteville, Wilmington, Jacksonville, Lumberton");
$L("SE Georgia");
$L("Southeastern Georgia: Savannah, Statesboro, Vidalia, Waycross, Brunswick, Douglas");
$L("E Kansas");
$L("Eastern Kansas: Kansas City, Overland Park, Paola, Leavenworth");
$L("New York");
$L("New York: Westchester County");
$L("Texas");
$L("Texas: El Paso County, Hudspeth County");
$L("California");
$L("Central California: Sacramento, Davis, Roseville");
$L("New York");
$L("New York: New York City");
$L("NE Oklahoma");
$L("Northeastern Oklahoma: Tulsa, Bartlesville, McAlester, Muskogee, Henryetta");
$L("North Carolina");
$L("North Central North Carolina: Raleigh, Durham, Chapel Hill, Oxford, Goldsboro");
$L("E Wisconsin");
$L("Eastern Wisconsin: Appleton, Sheboygan, Oshkosh, Green Bay, Manitowoc, Fond du Lac");
$L("California");
$L("Central California: Concord, Pleasant Hill, Walnut Creek, Martinez, Livermore, Pleasanton, Dublin");
$L("NW Arizona");
$L("Northern and Western Arizona: Flagstaff, Kingman, Prescott, Yuma");
$L("New York");
$L("Tennessee");
$L("Tennessee: Clarksville, Columbia, Manchester, Cookeville");
$L("S California");
$L("Southern California: San Diego");
$L("SE Texas");
$L("Central and Southeastern Texas: Nacogdoches, Lufkin, Conroe, Huntsville");
$L("SW Ohio");
$L("Southwestern Ohio: Marysville, Springfield, Dayton, Hillsboro");
$L("Alabama");
$L("Alabama: Huntsville");
$L("Puerto Rico");
$L("N Texas");
$L("Northern Texas: Vernon, Wichita Falls, Denton, Gainesville, Decatur");
$L("SW Florida");
$L("Southwestern Florida: Tampa Bay,Manatee County, Sarasota County, Charlotte County; Bradenton, Port Charlotte, Sarasota, Punta Gorda");
$L("Michigan");
$L("S California");
$L("Southern California: Laguna Niguel, Irvine, Lake Forest, Newport Beach, Corona Del Mar");
$L("Carrier Access");
$L("S California");
$L("Southern California: Corona, Riverside, Temescal Canyon, Lake Elsinore, Mira Loma, Moreno Valley, Perris, Sun City, Murrieta, Temecula, Hemet, Winchester, Lakeview, Nuevo, Beaumont, Banning, Idyllwild");
$L("Minnesota");
$L("Minnesota: Bloomington, Minnetonka, Chaska, Minneapolis");
$L("S Florida");
$L("Southern Florida: Fort Lauderdale, Hollywood, Coral Springs");
$L("S Texas");
$L("Southern Texas: Laredo, Brownsville, McAllen, Harlingen");
$L("Connecticut");
$L("NW Colorado");
$L("Northern and Western Colorado: Aspen, Durango, Grand Junction, Fort Collins");
$L("NW Oregon");
$L("Northwestern Oregon: Portland, Salem, Hillsboro, Beaverton");
$L("Texas");
$L("NW New Jersey");
$L("Northwestern New Jersey: Newark, Paterson");
$L("Missouri");
$L("NE Massachusetts");
$L("Northeastern Massachusetts: Fitchburg, Peabody");
$L("SE Texas");
$L("Southeastern Texas: Wharton, Bryan, Bay City, College Station, Lake Jackson, La Grange");
$L("North Carolina");
$L("North Carolina");
$L("SE Louisiana");
$L("Southeastern Louisiana: Houma, Slidell");
$L("Michigan");
$L("Central Michigan: Alpena, Mt. Pleasant, Bay City, Saginaw, Midland, Owosso");

